global using AsmResolver.DotNet;
global using AsmResolver.DotNet.Code.Cil;
global using AsmResolver.DotNet.Collections;
global using AsmResolver.DotNet.Signatures;
global using AsmResolver.PE.DotNet.Cil;
global using AsmResolver.PE.DotNet.Metadata.Tables;
global using System;
global using System.Collections.Generic;
global using System.Linq;