name: Build

on:
   push:
    branches: [ master ]
   workflow_dispatch:
  

jobs:
    build:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout Dumper Repository
       uses: actions/checkout@v2
     - name: Setup .NET
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 6.0.x
     - name: Build
       run: dotnet build /p:Configuration=Release
       working-directory: ./AssemblyDumper/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
      
     - name: Make scripts executable
       shell: bash
       run: |
        chmod +x ./generate_all.sh
        chmod +x ./get_names.sh
      
     - name: Run Generation
       shell: bash
       run: ./generate_all.sh

     - name: Force Push Assemblies To Branch
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: /home/runner/work/AssemblyDumper/AssemblyDumper/Output/
         publish_branch: v_development
         force_orphan: true
         enable_jekyll: true