name: Build

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
    build:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout Dumper Repository
       uses: actions/checkout@v2
     - name: Setup .NET
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 6.0.x
         include-prerelease: true
     - name: Build
       run: dotnet build /p:Configuration=Release
       working-directory: ./AssemblyDumper/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'ds5678/TypeTreeDumps'
        path: TypeTreeDumps
      
     - name: List Files
       shell: bash
       run: ls -R ./