name: Build

on:
   push:
    branches: [ master ]
   workflow_dispatch:
  

jobs:
    build:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout Dumper Repository
       uses: actions/checkout@v2
     - name: Setup .NET
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 6.0.x
     - name: Build
       run: dotnet build /p:Configuration=Release
       working-directory: ./AssemblyDumper/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
      
     - name: Run Generation
       shell: bash
       run: |
        chmod +x ./generate_all.sh
        ./generate_all.sh

     - name: Push Assemblies To Branch
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: v_development
         directory: /home/runner/work/AssemblyDumper/AssemblyDumper/Output/
         force: true