name: Test Parallelism

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]
   workflow_dispatch:
  

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Setup .NET
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 6.0.x
     - name: Build
       run: dotnet build /p:Configuration=Release
       working-directory: ./AssemblyDumper/

     - name: Upload AssemblyDumper
       uses: actions/upload-artifact@v2
       with:
         name: AssemblyDumper
         path: /home/runner/work/AssemblyDumper/AssemblyDumper/AssemblyDumper/bin/Release/net6/*
         if-no-files-found: error
      
    generate:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Download AssemblyDumper
       uses: actions/download-artifact@v2
       with:
        name: AssemblyDumper
        path: ./AssemblyDumper/bin/Release/net6/
     - name: Run Generation
       shell: bash
       run: |
        chmod +x ./AssemblyDumper/bin/Release/net6/AssemblyDumper
        chmod +x ./test.sh
        ./test.sh
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: TestAssemblies
         path: /home/runner/work/AssemblyDumper/AssemblyDumper/Output/*
         if-no-files-found: error

    upload:
     needs: generate
     runs-on: ubuntu-latest
     steps:
     - name: Download Assemblies
       uses: actions/download-artifact@v2
       with:
        name: TestAssemblies
        path: ./Output/
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: TestAssemblies2
         path: /home/runner/work/AssemblyDumper/AssemblyDumper/Output/*
         if-no-files-found: error